#!/usr/bin/env node
// ponsmcp setup — interactive CLI wizard to configure the PonsMCP agent wallet.
// Zero external deps: uses node:readline, node:crypto, node:fs, node:os, node:path.

import { createInterface } from 'node:readline';
import { randomBytes } from 'node:crypto';
import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { privateKeyToAddress } from './crypto.js';

// ─── Pretty output helpers ───────────────────────────────────────────────────

const RESET = '\x1b[0m';
const BOLD  = '\x1b[1m';
const DIM   = '\x1b[2m';
const CYAN  = '\x1b[36m';
const GREEN = '\x1b[32m';
const YELLOW = '\x1b[33m';
const RED   = '\x1b[31m';
const BLUE  = '\x1b[34m';

function box(lines: string[], color = CYAN): void {
  const maxLen = Math.max(...lines.map(l => stripAnsi(l).length));
  const w = maxLen + 4;
  console.log(color + '┌' + '─'.repeat(w) + '┐' + RESET);
  for (const line of lines) {
    const pad = w - stripAnsi(line).length - 2;
    console.log(color + '│ ' + RESET + line + ' '.repeat(pad) + color + ' │' + RESET);
  }
  console.log(color + '└' + '─'.repeat(w) + '┘' + RESET);
}

function stripAnsi(s: string): string {
  return s.replace(/\x1b\[[0-9;]*m/g, '');
}

function header(title: string): void {
  console.log('');
  box([
    BOLD + CYAN + '  PonsMCP Setup Wizard' + RESET,
    DIM  + '  ' + title + RESET,
  ]);
  console.log('');
}

function step(n: number, total: number, label: string): void {
  console.log(`\n${BOLD}${CYAN}[${n}/${total}]${RESET} ${BOLD}${label}${RESET}`);
  console.log(DIM + '─'.repeat(50) + RESET);
}

function ok(msg: string): void  { console.log(GREEN + '  ✓ ' + RESET + msg); }
function info(msg: string): void { console.log(BLUE  + '  ℹ ' + RESET + msg); }
function warn(msg: string): void { console.log(YELLOW + '  ⚠ ' + RESET + msg); }

// ─── Readline helpers ────────────────────────────────────────────────────────

function ask(rl: ReturnType<typeof createInterface>, prompt: string): Promise<string> {
  return new Promise(resolve => rl.question(prompt, resolve));
}

async function askWithDefault(
  rl: ReturnType<typeof createInterface>,
  label: string,
  def: string,
): Promise<string> {
  const answer = await ask(rl, `  ${label} ${DIM}[${def}]${RESET}: `);
  return answer.trim() || def;
}

// ─── Key generation ──────────────────────────────────────────────────────────

function generateKey(): { privHex: string; address: string } {
  const bytes = randomBytes(32);
  const privHex = '0x' + bytes.toString('hex');
  const privBigInt = BigInt('0x' + bytes.toString('hex'));
  const address = privateKeyToAddress(privBigInt);
  return { privHex, address };
}

// ─── Config writers ──────────────────────────────────────────────────────────

function writeEnvFile(cfg: Record<string, string>): string {
  const envPath = join(homedir(), '.ponsmcp.env');
  const lines = [
    '# PonsMCP agent wallet — generated by `ponsmcp setup`',
    '# Keep this file secret! It contains your private key.',
    '',
    ...Object.entries(cfg).map(([k, v]) => `${k}=${v}`),
    '',
  ];
  writeFileSync(envPath, lines.join('\n'), { mode: 0o600 });
  return envPath;
}

interface McpConfig {
  mcpServers?: Record<string, { command: string; args?: string[]; env?: Record<string, string> }>;
}

function upsertMcpConfig(configPath: string, envVars: Record<string, string>): void {
  let cfg: McpConfig = {};
  if (existsSync(configPath)) {
    try { cfg = JSON.parse(readFileSync(configPath, 'utf8')); } catch { /* fresh */ }
  } else {
    const dir = join(configPath, '..');
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  }
  if (!cfg.mcpServers) cfg.mcpServers = {};
  cfg.mcpServers['ponsmcp'] = {
    command: 'npx',
    args: ['-y', '@ponsmcp/sdk@latest'],
    env: envVars,
  };
  writeFileSync(configPath, JSON.stringify(cfg, null, 2) + '\n');
}

// ─── Main wizard ─────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  header('One-time wallet + policy configuration');

  // ── Step 1: Generate private key ──────────────────────────────────────────
  step(1, 5, 'Generate agent wallet');

  let privHex: string;
  let address: string;

  const existingKey = process.env.PONSMCP_PRIVATE_KEY;
  if (existingKey) {
    warn('PONSMCP_PRIVATE_KEY is already set in your environment.');
    const keep = await ask(rl, `  Keep the existing key? ${DIM}[Y/n]${RESET}: `);
    if (keep.trim().toLowerCase() !== 'n') {
      privHex = existingKey.startsWith('0x') ? existingKey : '0x' + existingKey;
      const privBigInt = BigInt(privHex);
      address = privateKeyToAddress(privBigInt);
      ok('Using existing wallet: ' + BOLD + address + RESET);
    } else {
      ({ privHex, address } = generateKey());
      ok('Generated new wallet: ' + BOLD + address + RESET);
    }
  } else {
    ({ privHex, address } = generateKey());
    ok('Generated new wallet: ' + BOLD + address + RESET);
  }

  console.log('');
  box([
    BOLD + '  Agent address:' + RESET,
    '  ' + CYAN + address + RESET,
    '',
    DIM + '  Private key stored in ~/.ponsmcp.env' + RESET,
    DIM + '  Never share this key!' + RESET,
  ], YELLOW);

  // ── Step 2: Funding instructions ──────────────────────────────────────────
  step(2, 5, 'Fund your agent wallet');

  console.log('');
  box([
    BOLD + '  Send to: ' + CYAN + address + RESET,
    '',
    '  • ' + YELLOW + 'ETH' + RESET + '  for gas   (≥ 0.005 ETH recommended)',
    '  • ' + YELLOW + 'USDG' + RESET + ' for payments (amount depends on your use case)',
    '',
    DIM + '  Chain: Robinhood Chain (chainId 4663)' + RESET,
    DIM + '  RPC:   https://rpc.nodeflare.app/robinhood/public' + RESET,
    DIM + '  Explorer: https://robinhoodchain.blockscout.com' + RESET,
  ], BLUE);

  await ask(rl, `\n  ${DIM}Press Enter to continue...${RESET}`);

  // ── Step 3: Alchemy key ───────────────────────────────────────────────────
  step(3, 5, 'Alchemy API key (optional)');

  info('An Alchemy key improves RPC reliability. Leave blank to use the public endpoint.');
  const alchemyKey = (await ask(rl, `  Alchemy API key ${DIM}[Enter to skip]${RESET}: `)).trim();
  if (alchemyKey) {
    ok('Alchemy key set.');
  } else {
    info('Skipped — using public RPC endpoint.');
  }

  // ── Step 4: Policy caps ───────────────────────────────────────────────────
  step(4, 5, 'Payment policy caps');

  info('These caps protect your wallet from runaway agent spending.');
  const maxPerTx    = await askWithDefault(rl, 'Max USDG per transaction', '10');
  const dailyLimit  = await askWithDefault(rl, 'Daily USDG spending limit',  '100');

  ok(`Max per tx: ${BOLD}${maxPerTx} USDG${RESET}`);
  ok(`Daily limit: ${BOLD}${dailyLimit} USDG${RESET}`);

  // ── Step 5: Write config ──────────────────────────────────────────────────
  step(5, 5, 'Write config & register with Claude Desktop');

  const envCfg: Record<string, string> = {
    PONSMCP_PRIVATE_KEY: privHex,
    PONSMCP_MAX_PER_TX:  maxPerTx,
    PONSMCP_DAILY_LIMIT: dailyLimit,
  };
  if (alchemyKey) envCfg.PONSMCP_ALCHEMY_KEY = alchemyKey;

  // Write ~/.ponsmcp.env
  const envPath = writeEnvFile(envCfg);
  ok('Wrote ' + BOLD + envPath + RESET);

  // Build env map for MCP config (without exposing key to process env literally)
  const mcpEnv: Record<string, string> = { ...envCfg };

  // Claude Code project config (~/.claude.json)
  const claudeJsonPath = join(homedir(), '.claude.json');
  try {
    upsertMcpConfig(claudeJsonPath, mcpEnv);
    ok('Updated ' + BOLD + claudeJsonPath + RESET);
  } catch (e) {
    warn(`Could not update ${claudeJsonPath}: ${e}`);
  }

  // Claude Desktop config (Linux/Windows vs macOS)
  const desktopPaths = [
    join(homedir(), '.config', 'Claude', 'claude_desktop_config.json'),
    join(homedir(), 'Library', 'Application Support', 'Claude', 'claude_desktop_config.json'),
  ];
  let updatedDesktop = false;
  for (const dp of desktopPaths) {
    // Write to the first path that already exists, or the first one on the list
    if (existsSync(dp) || dp === desktopPaths[0]) {
      try {
        upsertMcpConfig(dp, mcpEnv);
        ok('Updated ' + BOLD + dp + RESET);
        updatedDesktop = true;
        break;
      } catch (e) {
        warn(`Could not update ${dp}: ${e}`);
      }
    }
  }
  if (!updatedDesktop) {
    warn('Claude Desktop config not found; MCP entry not registered automatically.');
  }

  rl.close();

  // ── Success summary ───────────────────────────────────────────────────────
  console.log('');
  box([
    BOLD + GREEN + '  Setup complete! 🎉' + RESET,
    '',
    '  Agent address : ' + CYAN + address + RESET,
    '  Max per tx    : ' + BOLD + maxPerTx  + ' USDG' + RESET,
    '  Daily limit   : ' + BOLD + dailyLimit + ' USDG' + RESET,
    '',
    BOLD + '  Next steps:' + RESET,
    '  1. Fund the agent address with ETH + USDG on Robinhood Chain 4663',
    '  2. Restart Claude Desktop (or reload the MCP server)',
    '  3. Ask Claude: "What is my pons agent balance?"',
    '',
    DIM + '  Env file  : ' + envPath + RESET,
    DIM + '  To reload : source ~/.ponsmcp.env' + RESET,
  ], GREEN);

  console.log('');
}

main().catch(err => {
  console.error(RED + 'Setup failed: ' + err.message + RESET);
  process.exit(1);
});
